site_name: Michael

site_url: https://github.com/MioniMichael/ProvaSito

plugins:
  - search:
      lang: ['it', 'en']

theme:
  name: 'material'
  language: 'it'

nav:
  - Esempi 1: Pagine/Pagina1.md
  - Esempi 2: Pagine/Pagina2.md
  - MAIN: index.md